# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 601)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(810, 601))
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(810, 580))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 52, 581))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_schedule = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_schedule.setEnabled(True)
        self.pushButton_schedule.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_schedule.setStyleSheet("#pushButton_schedule{\n"
"border-image: url(:/1_schedule/1_schedule_up.jpg)\n"
"}\n"
"#pushButton_schedule:pressed{\n"
"border-image: url(:/1_schedule/1_schedule_down.jpg)\n"
"}")
        self.pushButton_schedule.setText("")
        self.pushButton_schedule.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_schedule.setObjectName("pushButton_schedule")
        self.verticalLayout.addWidget(self.pushButton_schedule)
        self.pushButton_add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_add.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_add.setStyleSheet("#pushButton_add{\n"
"border-image: url(:/2_add/2_add_up.jpg)\n"
"}\n"
"#pushButton_add:pressed{\n"
"border-image: url(:/2_add/2_add_down.jpg)\n"
"}")
        self.pushButton_add.setText("")
        self.pushButton_add.setObjectName("pushButton_add")
        self.verticalLayout.addWidget(self.pushButton_add)
        self.pushButton_analytics = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_analytics.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_analytics.setStyleSheet("#pushButton_analytics{\n"
"border-image: url(:/3_analytics/3_analytics_up.jpg)\n"
"}\n"
"#pushButton_analytics:pressed{\n"
"border-image: url(:/3_analytics/3_analytics_down.jpg)\n"
"}")
        self.pushButton_analytics.setText("")
        self.pushButton_analytics.setObjectName("pushButton_analytics")
        self.verticalLayout.addWidget(self.pushButton_analytics)
        self.widget_parent = QtWidgets.QWidget(self.centralwidget)
        self.widget_parent.setGeometry(QtCore.QRect(60, 0, 751, 581))
        self.widget_parent.setObjectName("widget_parent")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
